CREATE DATABASE IF NOT exists mercado_construcao;

USE mercado_construcao;


CREATE TABLE IF NOT EXISTS produtos (
id INT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(100) NOT NULL,
descricao TEXT,
preco DECIMAL(10,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS vendas(
id INT AUTO_INCREMENT PRIMARY KEY,
data_venda DATETIME DEFAULT CURRENT_TIMESTAMP,
valor_total DECIMAL (10,2) NOT NULL);

CREATE TABLE IF NOT EXISTS users(
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    sexo ENUM('M', 'F'),
    email VARCHAR(150) NOT NULL,
    senha VARCHAR(150) NOT NULL
);